### ISSUE TITLE
memod doesn't work with slack

### ISSUE THREAD

**Issue by valafon** [raintank/memo#18]
I created an application in Slack, gave the bot all permissions available, enabled the socket, and enabled event subscription. Memod is crashing, every time I type a message in chat, it doesn't matter which message. There are logs:

time="2023-06-26T09:06:22Z" level=info msg="Can talk to Grafana version 9.3.2 - its database is ok"
time="2023-06-26T09:06:22Z" level=info msg="Memo starting"
time="2023-06-26T09:06:22Z" level=info msg="slack enabled"
time="2023-06-26T09:06:22Z" level=info msg="Connecting to slack"
time="2023-06-26T09:06:23Z" level=info msg="Socket connected"
time="2023-06-26T09:06:23Z" level=info msg="Received hello from slack, hi!"
time="2023-06-26T09:06:38Z" level=trace msg="Received message `\"test\"`, not for us. ignoring"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6e9431]

goroutine 33 [running]:
github.com/grafana/memo.(*Memo).BuildTags(...)
	/opt/memo/memo.go:36
github.com/grafana/memo/service/slack.(*SlackService).handleMessage(0xc0002344d0, 0xc0001668c0)
	/opt/memo/service/slack/slack.go:98 +0x2d1
github.com/grafana/memo/service/slack.New.func1()
	/opt/memo/service/slack/slack.go:162 +0x413
created by github.com/grafana/memo/service/slack.New
	/opt/memo/service/slack/slack.go:133 +0x3e5

Tried to use 1.20 Go version and nothing really helps. Is memo capable to work with slack today, or maybe the code is outdated?

**Comment by surdaft** [comment]
Hmm interesting, I'll need to do some testing and I am quite pushed for time at the moment. At a glance it looks as though; it is returning nil (https://github.com/grafana/memo/blob/master/service/slack/slack.go#L86C25-L86C25) due to identifying that the message isn't for memod, then continues on its day, when it shouldn't. In theory just checking if the `memo` var is nil and returning would resolve the issue.

I can take a look tomorrow, test it and release a patch to resolve it.

---

Again, apologies for the slow reply. :)

**Comment by surdaft** [comment]
I applied a fix now, apologies for that. When reimplementing the slack service I missed the store property. Additionally slack did not handle messages that were not for them very well, which I handled too.
